---
# Summary of Steps
# 1. Stop target database (if running)
#
- name: Oracle Database Refresh
  hosts: tgtservers 
  vars_files:
    - vars/database.yaml 

  tasks:
# Stop Target Database
    - include: tasks/shutdown_DB.yaml
      tags: shutdown

# Clean-up Target database server
    - include: tasks/delete_admin.yaml
      tags: cleanup
