---
# Summary of Steps
# 1. Stop target database (if running)
# 2. Unmount the filesystem on target server (if mounted)
# 3. Take snapshot of the source volumes on Pure
# 4. Mount the cloned volumes on target server
# 5. Bring up the database on target server in mount mode
# 6. Change the database name using nid
# 7. Rename the directories on cloned database
# 8. Bring up the database & change filenames
#
- name: Oracle Database Refresh
  hosts: z-oracle2
  vars_files:
    - vars/arrays.yaml
    - vars/devslob.yaml 

  tasks:
# Set Suffix
    - set_fact:
        suffix: "ansible{{ 1000 | random }}"
      run_once: yes

# Set-up
    - name: Copy change database name script
      template: src=templates/6_dbnewid.sh.j2 dest={{ tgt_dir }}/6_dbnewid.sh mode=0755

    - name: Copy rename database files sql
      template: src=templates/rename.sql.j2 dest={{ tgt_dir }}/rename.sql mode=0644

    - name: Copy rename datafiles script
      template: src=templates/7_renfs.sh.j2 dest={{ tgt_dir }}/7_renfs.sh mode=0755

    - name: Copy rename db datafiles script
      template: src=templates/8_rendbfiles.sh.j2 dest={{ tgt_dir }}/8_rendbfiles.sh mode=0755

    - name: Copy database shutdown script to target database server
      template: src=templates/shutdownDB.sh.j2 dest={{ tgt_dir }}/shutdownDB.sh mode=0755

    - name: Copy database startup Mount script to target database server
      template: src=templates/5_startup.sh.j2 dest={{ tgt_dir }}/5_startup.sh mode=0755

# Create Pure session
    - include: tasks/create_session.yaml

# Take Snapshot of database volumes
    - include: tasks/take_snapshot.yaml

# Stop Target Database
    - include: tasks/shutdown_DB.yaml

# Unmount Target volume
    - include: tasks/unmount_volume.yaml

# Copy Snapshot to target database volume
    - include: tasks/copy_volume.yaml

# Delete Snapshot of database volumes
    - include: tasks/delete_snapshot.yaml

# Mount Target volume
    - include: tasks/mount_volume.yaml

# Startup Mount Target Database
    - include: tasks/5_startup.yaml

# Change Database Name
    - name: Change database name 
      shell: '{{ tgt_dir }}/6_dbnewid.sh'
      args:
        chdir: "{{ tgt_dir }}"

# Rename target database file names
    - name: Rename Target database directories
      shell: 'mv -v {{ item.value.sourced }} {{ item.value.targetd }} > 7a_renfs.log 2>&1'
      args:
        chdir: "{{ tgt_dir }}"
      with_dict: "{{ volmap }}" 

    - name: Create rename datafile script
      shell: '{{ tgt_dir }}/7_renfs.sh > 7b_renfs.log 2>&1'
      args:
        chdir: "{{ tgt_dir }}"

# Rename target database file names
    - name: Rename Target database file names
      shell: '{{ tgt_dir }}/8_rendbfiles.sh > 8_rendbfiles.log 2>&1'
      args:
        chdir: "{{ tgt_dir }}"
