---
######################################################
# Delete database snapshot on FlashArray
- name: Delete PURE Database Snapshot
  hosts: z-oracle2 
  gather_facts: no

  vars:
      pure_array: "{{ se_EMEA_EBC_m20 }}"
      target: "{{ devslob }}"
 
  tasks:
# Create Pure session
    - include: tasks/create_session.yml

# Perform Delete PURE Flasharray snaphot
    - name: perform PURE delete snapshot
      uri:
        url: https://{{ pure_array.ip }}/api/{{ pure_array.version }}/volume/{{ item.value.source }}.ansible176
        method: DELETE
        HEADER_Content-Type: "application/json"
        HEADER_Cookie: "{{session.set_cookie}}"
        validate_certs: "no"
        return_content: "yes"
      ignore_errors: yes
      with_dict: "{{ target }}"

# Eradicate PURE Flasharray snaphot
    - name: eradicate PURE snapshot
      uri:
        url: https://{{ pure_array.ip }}/api/{{ pure_array.version }}/volume/{{ item.value.source }}.ansible176?eradicate=true
        method: DELETE
        HEADER_Content-Type: "application/json"
        HEADER_Cookie: "{{session.set_cookie}}"
        validate_certs: "no"
        return_content: "yes"
      ignore_errors: yes
      with_dict: "{{ target }}"
      
