---
#######################################################
# Mount database file systems 
- name: Mount DB filesystems
#  hosts: dbservers
  hosts: z-oracle2
  gather_facts: no
  vars:
      dbmounts: "{{ devslob }}"

  tasks:

  - name: mount database filesystems
# use ansible mount module
    mount: name={{ item.value.name }} state=mounted src={{ item.value.src }} fstype={{ item.value.fstype }}
    become: true
    with_dict: "{{ dbmounts }}"
    tags:
    - mount
