- name: Pure Storage Ansible module Demo
  hosts: localhost 
  vars_files:
    - vars/demo.yaml

  gather_facts: false

  tasks:

  - name: Restore Pure FlashArray Volume
    purefa_volume:
      name: "{{ pgName }}.RON.{{ volName }}1"
      target: "{{ volName}}1"
      overwrite: yes
      fa_url: "{{ faUrl }}"
      api_token: "{{ apiToken }}"
      state: present

