---
######################################################
# Snapshot Database volumes on FlashArray
- name: PURE Database Snapshot
  hosts: z-oracle2 
  gather_facts: no

  vars:
    pure_array: "{{ se_EMEA_EBC_m20 }}"
    source: "{{ slob }}"
    target: "{{ devslob }}"
    volmap: "{{ tgtmap }}"
 
  tasks:

# Set Suffix
    - set_fact:
        suffix: "ansible{{ 1000 | random }}"
      run_once: yes

# Create Pure session
    - include: tasks/create_session.yml

# Take Snapshot of database volumes
    - include: tasks/take_snapshot.yml

# Unmount Target volume
    - include: tasks/unmount_volume.yml

# Copy Snapshot to target database volume
    - include: tasks/copy_volume.yml

# Delete Snapshot of database volumes
    - include: tasks/delete_snapshot.yml

# Mount Target volume
    - include: tasks/mount_volume.yml
