---
#######################################################
# Shutdown Oracle database 
- name: Shutdown Oracle Database 
  hosts: z-oracle2 
  gather_facts: no
  vars:
    tgt_db: devslob
    tgt_oh: /u01/app/oracle/product/12.1.0/dbhome_1
    tgt_dir: ~/.ansible

  tasks:

    - name: Copy database shutdown script to target database server
      template: src=templates/shutdownDB.sh.j2 dest={{ tgt_dir }}/shutdownDB.sh mode=0755

# Stop Target Database
    - include: tasks/shutdown_DB.yaml
