---
######################################################
# Snapshot Database volumes on FlashArray
- name: PURE Database Snapshot
  hosts: z-oracle2 
  gather_facts: no

  vars:
      pure_array: "{{ se_EMEA_EBC_m20 }}"
      source: "{{ slob }}"
      suffix: ansible{{ 1000 | random }}
 
  tasks:
# Create Pure session
    - include: tasks/create_session.yml

# Take Snapshot of database volumes
    - include: tasks/take_snapshot.yml
