---
# Delete audit and diag directories 
- name: Delete Source Oracle audit and diag directories
# use ansible file module
  file: 
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ tgt_ob }}/diag/rdbms/{{ src_db }}/{{ src_db }}"
    - "{{ tgt_ob }}/admin/{{ src_db }}"
  tags: setup

- name: Delete Target Oracle audit and diag directories
# use ansible file module
  file: 
    path: "{{ item }}"
    state: absent
    mode:  0750 
  loop:
    - "{{ tgt_ob }}/diag/rdbms/{{ tgt_db }}/{{ tgt_db }}"
    - "{{ tgt_ob }}/admin/{{ tgt_db }}"
  tags: setup

