---
# Create Pure session
- name: Create PURE Session
  uri:
    url: https://{{ arrayT.ip }}/api/{{ arrayT.api_version }}/auth/session
    method: POST
    headers:
      Content-Type: "application/json"
    validate_certs: "no"
    return_content: "yes"
    body:
        api_token: "{{ arrayT.array_token }}"
    body_format: json
  register: sessionT

- name: check progress of snapshot replication
  uri:
    url: https://{{ arrayT.ip }}/api/{{ arrayT.api_version }}/pgroup?names={{ array.name}}:{{ sourceName }}&snap=true&transfer=true&sort=created-&limit=1
    method: GET
    headers:
      Cookie: "{{ sessionT.set_cookie }}"
    validate_certs: "no"
    return_content: "yes"
  ignore_errors: yes
  register: replicate
# Delay 10 seconds, Retry 6 times
  until: replicate.json[0].progress == 1.0
  delay: 10
  retries: 30

- debug:
    msg: "Snapshot: {{ replicate.json[0].name }} Async Replication complete, {{ replicate.json[0].data_transferred }} bytes transferred"
