---
databases:
  
#Source database volumes
oraslob:
- z-oracle1-u02
- z-oracle1-u03

#Target database volumes
devslob:
  z-oracle2-u02:
   name:   /u02 
   src:    /dev/sdd 
   fstype: ext4
  z-oracle2-u03: 
   name:   /u03
   src:    /dev/sde
   fstype: ext4

#Target database volume mappings
tgtmap:
  vol1:
   source:  z-oracle1-u02
   sourced: /u02/oradata/oraslob
   target:  z-oracle2-u02
   targetd: /u02/oradata/devslob
  vol2:
   source:  z-oracle1-u03
   sourced: /u03/redologs/oraslob
   target:  z-oracle2-u03
   targetd: /u03/redologs/devslob
